export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_REQUEST_SUCCESS = 'PRODUCT_LIST_REQUEST_SUCCESS';
export const PRODUCT_LIST_REQUEST_FAIL = 'PRODUCT_LIST_REQUEST_FAIL';


export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_REQUEST_SUCCESS = 'PRODUCT_DETAIL_REQUEST_SUCCESS';
export const PRODUCT_DETAIL_REQUEST_FAIL = 'PRODUCT_DETAIL_REQUEST_FAIL';